### ISSUE TITLE
bioconductor-genomeinfodbdata postlink failure

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#13846]
It seems like suddenly, the genomeinfodbdata package cannot be installed anymore, because the post-link script fails. The failure reason is not shown by conda, and when I try to run the script manually, it seems to work. Any idea what could be wrong?

```
conda create -n test-genominfodbdata bioconductor-genomeinfodbdata
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/johannes/.local/opt/miniconda3/envs/test-genominfodbdata

  added / updated specs:
    - bioconductor-genomeinfodbdata


The following NEW packages will be INSTALLED:

  _r-mutex           pkgs/r/linux-64::_r-mutex-1.0.0-anacondar_1
  binutils_impl_lin~ pkgs/main/linux-64::binutils_impl_linux-64-2.28.1-had2808c_3
  binutils_linux-64  pkgs/main/linux-64::binutils_linux-64-7.2.0-had2808c_27
  bioconductor-geno~ bioconda/noarch::bioconductor-genomeinfodbdata-1.2.0-r351_0
  bwidget            pkgs/main/linux-64::bwidget-1.9.11-1
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2018.11.29-ha4d7672_0
  cairo              conda-forge/linux-64::cairo-1.14.12-h80bd089_1005
  curl               conda-forge/linux-64::curl-7.64.0-h646f8bb_2
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h2176d3f_1000
  freetype           conda-forge/linux-64::freetype-2.9.1-h94bbf69_1005
  gcc_impl_linux-64  pkgs/main/linux-64::gcc_impl_linux-64-7.2.0-habb00fd_3
  gcc_linux-64       pkgs/main/linux-64::gcc_linux-64-7.2.0-h550dcbe_27
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h9745a5d_1001
  gfortran_impl_lin~ pkgs/main/linux-64::gfortran_impl_linux-64-7.2.0-hdf63c60_3
  gfortran_linux-64  pkgs/main/linux-64::gfortran_linux-64-7.2.0-h550dcbe_27
  glib               conda-forge/linux-64::glib-2.56.2-had28632_1001
  graphite2          conda-forge/linux-64::graphite2-1.3.13-hf484d3e_1000
  gxx_impl_linux-64  pkgs/main/linux-64::gxx_impl_linux-64-7.2.0-hdf63c60_3
  gxx_linux-64       pkgs/main/linux-64::gxx_linux-64-7.2.0-h550dcbe_27
  harfbuzz           conda-forge/linux-64::harfbuzz-1.9.0-he243708_1001
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  krb5               conda-forge/linux-64::krb5-1.16.3-h05b26f9_1001
  libcurl            conda-forge/linux-64::libcurl-7.64.0-h541490c_2
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libffi             conda-forge/linux-64::libffi-3.2.1-hf484d3e_1005
  libgcc-ng          conda-forge/linux-64::libgcc-ng-7.3.0-hdf63c60_0
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.2.0-hdf63c60_3
  libiconv           conda-forge/linux-64::libiconv-1.15-h14c3975_1004
  libpng             conda-forge/linux-64::libpng-1.6.36-h84994c4_1000
  libssh2            conda-forge/linux-64::libssh2-1.8.0-h90d6eec_1004
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-7.3.0-hdf63c60_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h648cc4a_1001
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.8-h143f9aa_1005
  make               conda-forge/linux-64::make-4.2.1-h14c3975_2004
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1b-h14c3975_0
  pango              conda-forge/linux-64::pango-1.40.14-hf0c64fd_1003
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pixman             conda-forge/linux-64::pixman-0.34.0-h14c3975_1003
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  r-base             conda-forge/linux-64::r-base-3.5.1-he45234b_1005
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1000
  tktable            pkgs/main/linux-64::tktable-2.10-h14c3975_0
  wget               pkgs/main/linux-64::wget-1.19.5-h20c2e04_0
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.9-h14c3975_1004
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h4937e3b_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.7-h14c3975_1000
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.2-h14c3975_1007
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.3-h14c3975_1004
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h14c3975_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0'.
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /home/johannes/.local/opt/miniconda3/envs/test-genominfodbdata/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /home/johannes/.local/opt/miniconda3/envs/test-genominfodbdata/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
```

**Comment by AlexGa** [comment]
I have the same problem and checked the urls in the recipe. It seems that the version 1.2.0 is not available at https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata. Could this be the reason for the LinkError?

**Comment by johanneskoester** [comment]
It should try the first source first, which at least I could download when I tested. Of course, it won't hurt if the others would be there as well. @bgruening is there an expected delay in getting the sources up on depot?

**Comment by nsoranzo** [comment]
Just found the same issue for version 3.7.0 of bioconductor-org.dm.eg.db , bioconductor-org.hs.eg.db bioconductor-org.mm.eg.db , ... All missing from https://depot.galaxyproject.org/software/ .
See https://travis-ci.org/galaxyproject/tools-iuc/jobs/500101334 for https://github.com/galaxyproject/tools-iuc/pull/2320

**Comment by bgruening** [comment]
Ok, depot has problems. We will look into this today. But this issue seems to be unrelated to depot right? Depot is caching tarballs used during build-time. Depot has nothing to do with run-/install-time dependencies. Can it be that BioC is simply down or has changed URLs? Or is it just late and I miss something obvious?

**Comment by bgruening** [comment]
The first link also works for me https://bioconductor.org/packages/3.8/data/annotation/src/contrib/GenomeInfoDbData_1.2.0.tar.gz

Conda issue with post-scripts?

**Comment by nsoranzo** [comment]
> Depot is caching tarballs used during build-time. Depot has nothing to do with run-/install-time dependencies.

I am not up-to-date with bioconductor packages in Bioconda, but it seems that since https://github.com/bioconda/bioconda-recipes/pull/6505/files#diff-470b868b8f873e497edfdad44fdefd28 for annotation packages, `build.sh` has been removed in favour of `post-link.sh`, which means that packages on anaconda.org are almost empty and the actual download and installation happen at install time.

**Comment by bgruening** [comment]
> I am not up-to-date with bioconductor packages in Bioconda, but it seems that since [bioconda/bioconda-recipes/pull/6505/files#diff-470b868b8f873e497edfdad44fdefd28](https://github.com/bioconda/bioconda-recipes/pull/6505/files#diff-470b868b8f873e497edfdad44fdefd28) for annotation packages, `build.sh` has been removed in favour of `post-link.sh`, which means that packages on anaconda.org are almost empty and the actual download and installation happen at install time.

Yes this is correct. But still has nothing to do with depot atm and also not with this issue I think. The tarball in question (
bioconductor.org/packages/3.8/data/annotation/src/contrib/GenomeInfoDbData_1.2.0.tar.gz) is downloadable. So the error has nothing to do with a wrong link or something like that, isn't it?

**Comment by nsoranzo** [comment]
> So the error has nothing to do with a wrong link or something like that, isn't it?

You are right, this seems to be a [conda 4.6 bug](https://github.com/conda/conda/issues/8306).

**Comment by bgruening** [comment]
Closing as a conda bug and not a bioconda issue.

**Comment by bgruening** [comment]
However, @johanneskoester if you can figure out what is missing from the R packages in the environment, so the real error. We might want to enhance our recipes during the next rebuild. Maybe `md5sum` is missing in the run-deps?

Cargo-port should work again.

**Comment by johanneskoester** [comment]
I'll try to figure it out today.

**Comment by johanneskoester** [comment]
So, it seems like the wget from conda-forge has an SSL problem. When I deactivate the -q, I get `Disabling SSL due to encountered errors.` and the download fails.

**Comment by johanneskoester** [comment]
Actually the wget seems to come from the anaconda channel. We could switch to curl, which should be installed on any system without the need to depend on a package.

**Comment by jdblischak** [comment]
I got the post-link error using conda 4.4.10, 4.5.12, and 4.6.7. As a temporary workaround, I was able to install GenomeInfoDbData by pinning `wget` to its previous version of [1.19.4](https://anaconda.org/anaconda/wget/files?version=1.19.4):

```
conda --version
## conda 4.6.7
conda create -n test-wget bioconductor-genomeinfodbdata wget=1.19.4
```

**Comment by bgruening** [comment]
This was fixed by a rebuild of wget against the newest openssl version.

**Comment by jenzopr** [comment]
Weird. On Conda `4.5.13`, it seems that `bioconductor-genomeinfodbdata` is fully non-functional, but installation does not throw an error:

```
$ conda create -n r-test bioconductor-genomeinfodb bioconductor-genomeinfodbdata

# No errors

$ conda activate r-test
$ R -e "library(GenomeInfoDbData)"
> library(GenomeInfoDbData)
Error in library(GenomeInfoDbData) : 
  there is no package called ‘GenomeInfoDbData’
Execution halted
```

A `conda list` reveals:

```
# packages in environment at /home/jpreuss/.conda/envs/r-test:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1  
binutils_impl_linux-64    2.31.1               h6176602_1  
binutils_linux-64         2.31.1               h6176602_3  
bioconductor-biocgenerics 0.28.0                   r351_1    bioconda
bioconductor-genomeinfodb 1.18.1                   r351_0    bioconda
bioconductor-genomeinfodbdata 1.2.0                    r351_0    bioconda
bioconductor-iranges      2.16.0           r351h14c3975_0    bioconda
bioconductor-s4vectors    0.20.1           r351h14c3975_0    bioconda
bwidget                   1.9.11                        1  
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_3    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_1  
gfortran_linux-64         7.3.0                h553295d_3  
glib                      2.58.3            hf63aee3_1001    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.4               h294904e_1005    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_3    conda-forge
harfbuzz                  2.4.0                h37c48d4_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
libidn2                   2.1.1                h14c3975_0    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libunistring              0.9.10               h14c3975_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
make                      4.2.1             h14c3975_2004    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
r-base                    3.5.1             h271c98b_1006    conda-forge
r-bitops                  1.0_6           r351h96ca727_1002    conda-forge
r-rcurl                   1.95_4.12        r351hcdcec82_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
tktable                   2.10                 h14c3975_0  
wget                      1.20.1               h90d6eec_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

but directory listing of `~/.conda/envs/r-test/lib/R/library` gives:
```
total 92
drwxr-xr-x 23 jpreuss jpreuss 4096 Apr 10 09:53 .
drwxr-xr-x 10 jpreuss jpreuss 4096 Apr 10 09:53 ..
drwxr-xr-x  7 jpreuss jpreuss 4096 Apr 10 09:53 base
drwxr-xr-x  7 jpreuss jpreuss 4096 Apr 10 09:53 BiocGenerics
drwxr-xr-x  7 jpreuss jpreuss 4096 Apr 10 09:53 bitops
drwxr-xr-x  6 jpreuss jpreuss 4096 Apr 10 09:53 compiler
drwxr-xr-x  6 jpreuss jpreuss 4096 Apr 10 09:53 datasets
drwxr-xr-x  9 jpreuss jpreuss 4096 Apr 10 09:53 GenomeInfoDb
drwxr-xr-x  8 jpreuss jpreuss 4096 Apr 10 09:53 graphics
drwxr-xr-x 11 jpreuss jpreuss 4096 Apr 10 09:53 grDevices
drwxr-xr-x  8 jpreuss jpreuss 4096 Apr 10 09:53 grid
drwxr-xr-x 11 jpreuss jpreuss 4096 Apr 10 09:53 IRanges
drwxr-xr-x  7 jpreuss jpreuss 4096 Apr 10 09:53 methods
drwxr-xr-x  8 jpreuss jpreuss 4096 Apr 10 09:53 parallel
drwxr-xr-x 14 jpreuss jpreuss 4096 Apr 10 09:53 RCurl
drwxr-xr-x 10 jpreuss jpreuss 4096 Apr 10 09:53 S4Vectors
drwxr-xr-x  7 jpreuss jpreuss 4096 Apr 10 09:53 splines
drwxr-xr-x  8 jpreuss jpreuss 4096 Apr 10 09:53 stats
drwxr-xr-x  6 jpreuss jpreuss 4096 Apr 10 09:53 stats4
drwxr-xr-x  9 jpreuss jpreuss 4096 Apr 10 09:53 tcltk
drwxr-xr-x  7 jpreuss jpreuss 4096 Apr 10 09:53 tools
drwxr-xr-x 20 jpreuss jpreuss 4096 Apr 10 09:53 translations
drwxr-xr-x 10 jpreuss jpreuss 4096 Apr 10 09:53 utils
```

**Comment by parlar** [comment]
Strangely, installation of bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0 works fine on Ubuntu 18.04 but not on Centos 7.6 where I need it.

As suggested in the previous issue, I have locked wget=1.19.4. Data does get downloaded but then it fails anyway.

Error msg says: ```location of failed script: /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh```. But the file is not there!

Below is the error, complete traceback for the failed installation on Centos. What can I do to further troubleshoot the issue?

```
TRACE conda.gateways.disk.create:_do_copy(284): copying /usr/local/share/bcbio/anaconda/envs/test-wget/conda-meta/history => /usr/local/share/bcbio/anaconda/envs/test-wget/conda-meta/history.c~
DEBUG conda.core.link:run_script(1078): for bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0 at /usr/local/share/bcbio/anaconda/envs/test-wget, executing script: $ bash /usr/local/share/bcbio/anaconda/envs/test-wget/.tmpe74wkyr7
DEBUG conda.gateways.subprocess:subprocess_call(69): executing>> bash /usr/local/share/bcbio/anaconda/envs/test-wget/.tmpe74wkyr7
INFO conda.gateways.subprocess:subprocess_call(83): $ bash /usr/local/share/bcbio/anaconda/envs/test-wget/.tmpe74wkyr7
==> cwd: /usr/local/share/bcbio/anaconda/envs/test-wget/bin <==
==> exit code: 1 <==
==> stdout <==
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 8fdbaf72a91aa676a3d521f0f307f10b:
https://bioconductor.org/packages/3.8/data/annotation/src/contrib/GenomeInfoDbData_1.2.0.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.0.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.0_src_all.tar.gz

==> stderr <==


TRACE conda.gateways.disk.delete:rm_rf(158): rm_rf /usr/local/share/bcbio/anaconda/envs/test-wget/.messages.txt
TRACE conda.gateways.disk.delete:rm_rf(164): rm_rf failed. Not a link, file, or directory: /usr/local/share/bcbio/anaconda/envs/test-wget/.messages.txt
TRACE conda.gateways.disk.delete:rm_rf(158): rm_rf /usr/local/share/bcbio/anaconda/envs/test-wget/.tmpe74wkyr7
DEBUG conda.core.link:_execute_post_link_actions(652): Error in post-link pkg_idx #0
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 1079, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/gateways/subprocess.py", line 85, in subprocess_call
    output=formatted_output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio/anaconda/envs/test-wget/.tmpe74wkyr7']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 649, in _execute_post_link_actions
    activate=True)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 1095, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0'.
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

INFO conda.core.link:_reverse_actions(680): ===> REVERSING PACKAGE LINK: bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0 <===
  prefix=/usr/local/share/bcbio/anaconda/envs/test-wget

DEBUG conda.core.link:_reverse_actions(682): reversing pkg_idx #0 from axn_idx #-1
TRACE conda.core.path_actions:reverse(872): reversing linked package record creation /usr/local/share/bcbio/anaconda/envs/test-wget/conda-meta/bioconductor-genomeinfodbdata-1.2.0-r351_0.json
TRACE conda.gateways.disk.test:file_path_is_writable(25): checking path is writable /usr/local/share/bcbio/anaconda/envs/test-wget/conda-meta/history
TRACE conda.gateways.disk.delete:rm_rf(158): rm_rf /usr/local/share/bcbio/anaconda/envs/test-wget/conda-meta/bioconductor-genomeinfodbdata-1.2.0-r351_0.json
TRACE conda.core.path_actions:reverse(373): reversing link creation /usr/local/share/bcbio/anaconda/envs/test-wget
TRACE conda.gateways.disk.delete:rm_rf(158): rm_rf /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-pre-unlink.sh
TRACE conda.core.path_actions:reverse(373): reversing link creation /usr/local/share/bcbio/anaconda/envs/test-wget
TRACE conda.gateways.disk.delete:rm_rf(158): rm_rf /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh
TRACE conda.core.path_actions:reverse(373): reversing link creation /usr/local/share/bcbio/anaconda/envs/test-wget
failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0'.
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: ...working... done
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGABRT
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGINT
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGTERM
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGQUIT
TRACE conda.gateways.disk.delete:rm_rf(158): rm_rf /usr/local/share/bcbio/anaconda/envs/test-wget/.condatmp
TRACE conda.gateways.disk.delete:rm_rf(164): rm_rf failed. Not a link, file, or directory: /usr/local/share/bcbio/anaconda/envs/test-wget/.condatmp
Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 1079, in run_script
    subprocess_call(command_args, env=env, path=dirname(path))
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/gateways/subprocess.py", line 85, in subprocess_call
    output=formatted_output)
subprocess.CalledProcessError: Command '['bash', '/usr/local/share/bcbio/anaconda/envs/test-wget/.tmpe74wkyr7']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 649, in _execute_post_link_actions
    activate=True)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 1095, in run_script
    raise LinkError(message)
conda.exceptions.LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 558, in _execute
    cls._execute_post_link_actions(pkg_idx_tracked, axngroup)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 664, in _execute_post_link_actions
    reverse_excs,
conda.CondaMultiError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
    return func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/install.py", line 275, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/cli/install.py", line 304, in handle_txn
    unlink_link_transaction.execute()
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 241, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/usr/local/share/bcbio/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 587, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/test-wget/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
```

**Comment by jenzopr** [comment]
Pinning wget fixed my issue with `4.5.13`.

**Comment by parlar** [comment]
Did not fix it for me. 

Downgraded to ```conda=4.5.13 wget=1.19.4``` ,  ran ```./conda clean -a```.

Then tried to install bioconductor-genomeinfodbdata using:

```./conda install -c bioconda bioconductor-genomeinfodbdata conda=4.5.13 wget=1.19.4```

But it fails with the usual error msg:

```
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0'.
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /home/pela09/bcbio/anaconda/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /home/pela09/bcbio/anaconda/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
```

I also copied the ```*link.sh``` scripts from the ```pkgs/bioconductor-genomeinfodbdata-1.2.0-r351_0/bin directory``` :
```
[pela09@vs478 anaconda]$ cp ./pkgs/bioconductor-genomeinfodbdata-1.2.0-r351_0/bin/.bioconductor-genomeinfodbdata-pre-unlink.sh bin
[pela09@vs478 anaconda]$ cp ./pkgs/bioconductor-genomeinfodbdata-1.2.0-r351_0/bin/.bioconductor-genomeinfodbdata-post-link.sh bin
```

Trying again, it fails the same way and the ```*link.sh``` scripts are gone from the ```anaconda/bin``` directory.

**Comment by dpryan79** [comment]
Xref #14421 And I'll add that we just ran into this in our pipelines. I start working on this today.

**Comment by dpryan79** [comment]
Hmm, this works for me for some reason. Can those of you still experiencing this please try again after doing the following?

 - Find and remove all environments with `bioconductor-genomeinfodb` and `bioconductor-genomeinfodbdata`
 - Run `conda clean -all`
 - Create a new env with `bioconductor-genomeinfodb`

**Comment by bgruening** [comment]
@dpryan79 we see it on travis as well. https://github.com/bgruening/galaxytools/pull/857
This should be a clean environment.

**Comment by dpryan79** [comment]
Yeah, since this is happening in the mulled test too it’s definitely an innate issue. I wish it were easier to reproduce locally.

**Comment by bernt-matthias** [comment]
Had the same problem with the dada2 package. Upgrading to conda-4.6.14, cleaning everything and reinstalling solved it for me.

**Comment by bgruening** [comment]
I can confirm, if you update the conda version it seems to work.

Please reopen, if this is still an issue.

**Comment by dpryan79** [comment]
Interesting, so this is a conda version thing? How weird. That suggests that we just need to finish updating conda in the mulled container, since we have PRs breaking due to this.

**Comment by bernt-matthias** [comment]
Question for the Galaxy users: is it safe to update conda for a galaxy installation?

**Comment by dpryan79** [comment]
@bernt-matthias I upgraded the conda used by our Galaxy instance, but that was quite a while ago (I think it was the transition from the shorter to longer conda prefix). A good question becomes whether Galaxy handles conda 4.6 properly, since the `conda` executable itself has moved from `$PREFIX/bin`.

@erasche What conda version is galaxy.eu using, or are you purely on docker/singularity containers now?

**Comment by nsoranzo** [comment]
Galaxy works fine with 4.6 , conda path is derived from `conda_exec` or `conda_prefix` as defined in `config/galaxy.yml` , not from within the environment.

**Comment by parlar** [comment]
It turns out that the issue for me was that conda does not see ca-certs despite beling explicity set.

Now the genomeinfodb package was modified to use curl instead of wget but the problem remained since it was due to conda.

The solution was to set ```export SSL_CERT_FILE=/path/to/ca.pem``` which makes curl work as intended. The package then installed fine.

Since it's a conda problem, I've entered an issue here: https://github.com/conda/conda/issues/8653

I used:
CentOS Linux release 7.6.1810 (Core)
Conda is version 4.6.14

**Comment by parlar** [comment]
Another update:

mingwandroid just wrote: "Conda's ssl settings pertain only to conda itself and not to and other packages you can install via conda."  (https://github.com/conda/conda/issues/8653)

That means that installation of conda packages that depend on programs like wget or curl will always fail if you're inside a corporate network. In this case it was also very cryptic, not at all clear why it failed. 

Is it possible, within the post-link script to set the path to the ca-cert, perhaps by asking conda what it is?

**Comment by DeKegel** [comment]
I'm still seeing this issue in both conda versions 4.6.14 and 4.7.12. I've tried the various suggestions in this thread, including deleting all environments and running a `conda clean --all`. Any ideas on what could be going wrong?

This:
`conda create -n r-test bioconductor-genomeinfodbdata`

Still results in:
```
Executing transaction: / ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.2-r36_0'.
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.2-r36_0
running your command again with `-v` will provide additional information
location of failed script: /Users/barbaradekegel/opt/anaconda3/envs/r-test/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

Attempting to roll back.
```

Some info that might be relevant:
conda version : 4.6.14
conda-build version : 3.18.9
python version : 3.7.4.final.0
platform : osx-64

**Comment by yhw320** [comment]
> > 我对Bioconda中的bioconductor包不是最新的，但似乎自从[bioconda/bioconda-recipes/pull/6505/files#diff-470b868b8f873e497edfdad44fdefd28](https://github.com/bioconda/bioconda-recipes/pull/6505/files#diff-470b868b8f873e497edfdad44fdefd28)注释以来包，`build.sh`已被删除以支持`post-link.sh`，这意味着包anaconda.org几乎是空的，实际的下载和安装是在安装时发生的。
> 
> 是的，这是正确的。但我认为仍然与仓库自动取款机相关，也与这个问题相关。压缩包有问题（ bioconductor.org/packages/3.8/data/annotation/src/contrib/GenomeInfoDbData_1.2.0. tar.gz) 是可下载的。所以这个错误与错误的链接或类似的东西相关，不是吗？

All three of the sites where R packages are stored appear to be down.
  url:
    - https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.9.tar.gz
    - https://bioconductor.org/packages/3.16/data/annotation/src/contrib/GenomeInfoDbData_1.2.9.tar.gz
    - https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.9_src_all.tar.gz

**Comment by mailmrcai** [comment]
This method works for me. When installing Monocle 3, specifying the version of genomeinfodbdata at the same time allows me to bypass the errors.  `mamba install r-monocle3 bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2`

**Comment by HaileyHryPark** [comment]
I was having the same error when I was installing genomeinfodbdata version 1.2.11.
I followed the above comment to try installing genomeinfodbdata version 1.2.7 instead, and had an incompatibility issue with Seurat 5.0.1 as follows:
![image](https://github.com/user-attachments/assets/ac3572be-0fc3-4eea-884f-fc41afbffca3)

I tried my luck by installing **genomeinfodbdata version 1.2.10** with Seurat 5.0.1, and I did not get any error anymore installing them together!

Hope this helps anyone having a similar problem.

**Comment by BoTang1** [comment]
Hello guys,
  I still have the issue to install "GenomeInfoDbData_1.2.11.tar.gz". I firstly tried to downloaded it and installed mannually in R session, but when I used "conda list" to check that package, I still can not find that, it might show I didnot install successfully.

Then I tried to use code: "conda install bioconda::bioconductor-genomeinfodb". I got errors as showing in the following figure.
My R version: 4.3.3,
conda version: 23.7.4
![2](https://github.com/user-attachments/assets/143c536f-a2eb-48aa-8da8-e2dc1f68052c)
Does anyone have suggestions how to solve this problem? I searched many materials, and I still cannot solve it.

**Comment by dschnei1** [comment]
Hi guys,
same issue for me - it seemed to work at some point recently, but now I have the same problem as mentioned by BoTang1.
I tried to install DESeq2 via mamba, then I tried to manually install it afterwards via shell and got this:

**trying URL 'https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz'
Content type 'application/gzip' length 12284235 bytes (11.7 MB)
===============
downloaded 3.6 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  download from 'https://bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz' failed
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 0 != reported length 0
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://mghp.osn.xsede.org/bir190004-bucket01/archive.bioconductor.org/packages/3.18/data/annotation/src/contrib/GenomeInfoDbData_1.2.11.tar.gz': status was 'Transferred a partial file'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘GenomeInfoDbData’ failed**

So maybe the download for this particular package is somewhat broken?

**Comment by colinbrislawn** [comment]
>So maybe the download for this particular package is somewhat broken?

Yes, I think so. I've had this problem on and off for years.

Maybe we could include the DB inside the conda package, perhaps by adding the download the to build.sh script so the package only build when it can download and bundle the DB.

Basically, we cache the database on conda and get it from conda, so we don't have to rely the first-party servers.
