### ISSUE TITLE
htslib on OSX requires libdeflate.so not libdeflate.dylib

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-recipes#15415]
This breaks new metabat recipe. Need to investigate. Either libdeflate needs a symlink as `libdeflate.so` on OSX or the names in htslib need fixings. Curious it worked during build...

**Comment by kyleabeauchamp** [comment]
I recall there were a few libdeflate version bumps recently as well, not sure what happened.

**Comment by epruesse** [comment]
```
$ otool -L libhts.1.9.dylib
libhts.1.9.dylib:
	@rpath/libhts.2.dylib (compatibility version 2.0.0, current version 1.9.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	@rpath/libdeflate.so (compatibility version 0.0.0, current version 0.0.0)
	@rpath/liblzma.5.dylib (compatibility version 8.0.0, current version 8.4.0)
	@rpath/libbz2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

The problem is the line `@rpath libdeflate.so`, which is one way or another wrong.

**Comment by kyleabeauchamp** [comment]
It might be useful to open an htslib ticket to confirm that there's not an issue upstream.  I'm not sure if this is due to the conda-magic or not.

**Comment by epruesse** [comment]
It's a build issue. Still tracing.

It started with htslib-1.8-1

**Comment by epruesse** [comment]
Ok, libdeflate contains the library misnamed as `.so` in versions: 

 - libdeflate-0.8-0
 - libdeflate-0.8-h470a237_2
 - libdeflate-1.0-h470a237_0
 - libdeflate-1.0-h1de35cc_1
 
Meaning it changed in libdeflate 1.2. Technically, libdeflate 1.2 was fixed, but the rename of the DSO means that nothing built against libdeflate <1.2 will work with libdeflate >=1.2.

**Comment by epruesse** [comment]
Grmbl. I'm getting an old htslib, which doesn't depend on libdeflate <1.1.0a0 yet. I *hate* that I get old builds. Why would you ever want an old build?

**Comment by epruesse** [comment]
```diff
--- htslib_pinned.txt	2019-05-15 22:19:03.000000000 -0600
+++ htslib_unpinned.txt	2019-05-15 22:19:23.000000000 -0600
@@ -1,12 +1,12 @@
   bzip2              conda-forge/osx-64::bzip2-1.0.6-h1de35cc_1002
   ca-certificates    conda-forge/osx-64::ca-certificates-2019.3.9-hecc5488_0
   curl               conda-forge/osx-64::curl-7.64.1-h22ea746_0
-  htslib             bioconda/osx-64::htslib-1.9-h3a161e8_7
+  htslib             bioconda/osx-64::htslib-1.9-h4da6232_2
   krb5               conda-forge/osx-64::krb5-1.16.3-hcfa6398_1001
   libcurl            conda-forge/osx-64::libcurl-7.64.1-h16faf7d_0
   libcxx             conda-forge/osx-64::libcxx-8.0.0-2
   libcxxabi          conda-forge/osx-64::libcxxabi-8.0.0-2
-  libdeflate         bioconda/osx-64::libdeflate-1.0-h1de35cc_1
+  libdeflate         bioconda/osx-64::libdeflate-1.2-h1de35cc_0
   libedit            conda-forge/osx-64::libedit-3.1.20170329-hcfe32e1_1001
   libssh2            conda-forge/osx-64::libssh2-1.8.2-hcdc9a53_2
   llvm-openmp        conda-forge/osx-64::llvm-openmp-8.0.0-h770b8ee_0
```

So `conda` decides that it would rather install the new version of libdeflate than the newer build of htslib. Unfortunately, that older build of htslib is broken in that it does not pin libdeflate. 

*Sigh*

**Comment by dpryan79** [comment]
Should we mark that old htslib broken on OSX and remove the main label?

**Comment by jmarshall** [comment]
Your current macOS HTSlib build (htslib-1.9-h3a161e8_7) still links against _@rpath/libdeflate.**so**_.

Apparently only libdeflate >= 1.1 was patched to provide _.dylib_ instead (PR #12809), yet [bioconda-utils](https://github.com/bioconda/bioconda-utils/blob/b4b4cafe7039e5dee598ccf207a9856ba896658c/bioconda_utils/bioconda_utils-conda_build_config.yaml) still pins libdeflate 1.0.

https://github.com/bioconda/bioconda-utils/blob/b4b4cafe7039e5dee598ccf207a9856ba896658c/bioconda_utils/bioconda_utils-conda_build_config.yaml#L24-L25

…?

**Comment by dpryan79** [comment]
Yeah, I just ran into this in another PR. I've marked the OSX builds of htslib 1.9 with broken pinning as "broken". I'm moving libdeflate to conda-forge and updating it to 1.3. We should then update the pinnings here on bioconda. In the interim this will probably work now (as of a couple hours ago).

**Comment by jpuritz** [comment]
Just an FYI, that this still isn't working quite right.  Just installed a created a new OSX environment that contained `samtools` and version `bioconda/osx-64::samtools-1.7-1` was installed with `conda-forge/osx-64::libdeflate-1.3-h01d97ff_0`.  This caused an error when trying to run `samtools`  

```
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/jpuritz/miniconda3/envs/ddocent/bin/samtools
  Reason: image not found
Abort trap: 6
```

I fixed this by running `conda update samtools` within the environment.  This led to:

```
The following packages will be UPDATED:

  samtools                                            1.7-1 --> 1.9-h7c4ea83_11

The following packages will be SUPERSEDED by a higher-priority channel:

  libdeflate         conda-forge::libdeflate-1.3-h01d97ff_0 --> bioconda::libdeflate-1.0-h1de35cc_1
```

Now, `samtools` works again.

**Comment by dpryan79** [comment]
@jpuritz Thanks, I'm slowly putting together a list of old packages that need to have their metadata patched (at least we can do that now): https://github.com/bioconda/bioconda-recipes/issues/17212

**Comment by jpuritz** [comment]
Still having issues with this in the `dDocent` recipe.  A new environment is giving me:

```
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/jpuritz/miniconda3/envs/ddocent/bin/samtools
  Reason: image not found
Abort trap: 6
```

`conda update samtools` fixes this with:

```
The following packages will be UPDATED:

  htslib                                     1.8-h57f8fdf_2 --> 1.9-h3a161e8_7
  samtools                                          1.4.1-0 --> 1.9-h8aa4d43_12

The following packages will be SUPERSEDED by a higher-priority channel:

  libdeflate         conda-forge::libdeflate-1.3-h01d97ff_0 --> bioconda::libdeflate-1.0-h1de35cc_1
```

I'm not sure why this is happening or if it's happening just for me.  Two days ago, when I incremented the build on `dDocent`, the CircleCI builds use the proper version of `htslib` and `samtools` 

I can get it to install perfectly with this command: `conda create -n ddocent ddocent samtools`

**Comment by giggu98** [comment]
I still got issues with `Abort trap: 6 `
I tried updating samtools `conda update samtools`  but everything seems to be already up to date.
```
dyld: Library not loaded: @rpath/libdeflate.so
  Referenced from: /anaconda3/lib/libhts.2.dylib
  Reason: image not found
```

**Comment by zeissmania** [comment]
I got the same error when running bcftools. 

```
dyld: Library not loaded: @rpath/libdeflate.so
  Referenced from: ~/miniconda3/bin/bcftools
  Reason: image not found
[1]    30008 abort      bcftools query
```
I fixed it just by creating a symlink for libdeflate.so

```cd ~/miniconda3/lib
ln -s ibdeflate.dylib libdeflate.so
```

if you can find ibdeflate.dylib under ~/miniconda3/lib, you may try this.

**Comment by dpryan79** [comment]
@zeissmania can you run `conda list | grep samtools` in that env? This should have been fixed for a few months now.

**Comment by nh13** [comment]
@dpryan79 on OXS
```
$conda list | grep samtools
samtools                  1.9                 h8aa4d43_12    bioconda
$ conda list | grep htslib
htslib                    1.9                  h4da6232_2    bioconda/label/broken
$ conda list | grep libdeflate
libdeflate                1.3                  h01d97ff_0    conda-forge
```

**Comment by dpryan79** [comment]
@nh13 There's a reason that htslib build has a broken label. Newer builds of htslib 1.9 have this fixed.

**Comment by nh13** [comment]
@dpryan79 this was part of a previous `conda env export` prior to the fix.  Unfortunately neither `conda update -c bioconda samtools` nor `conda update -c bioconda htslib` seems to update the packages.  I can't try installing a specific version and build.   I wonder if it ever worked.

**Comment by alanwilter** [comment]
I still can't get `htslib` working on my mac, even if `libdeflate` looks "fine". I'm trying this:
```bash
conda create -n atest  htslib
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/Caskroom/miniconda/base/envs/atest

  added / updated specs:
    - htslib


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/osx-64::bzip2-1.0.8-haf1e3a3_3
  c-ares             conda-forge/osx-64::c-ares-1.16.1-haf1e3a3_3
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.6.20-hecda079_0
  htslib             bioconda/osx-64::htslib-1.11-h422799e_0
  krb5               conda-forge/osx-64::krb5-1.17.1-h75d18d8_3
  libcurl            conda-forge/osx-64::libcurl-7.71.1-h9bf37e3_8
  libcxx             conda-forge/osx-64::libcxx-11.0.0-h439d374_0
  libdeflate         conda-forge/osx-64::libdeflate-1.6-h0b31af3_0
  libedit            conda-forge/osx-64::libedit-3.1.20191231-h0678c8f_2
  libev              conda-forge/osx-64::libev-4.33-haf1e3a3_1
  libnghttp2         conda-forge/osx-64::libnghttp2-1.41.0-h7580e61_2
  libssh2            conda-forge/osx-64::libssh2-1.9.0-h8a08a2b_5
  ncurses            conda-forge/osx-64::ncurses-6.2-hb1e8313_2
  openssl            conda-forge/osx-64::openssl-1.1.1h-haf1e3a3_0
  tk                 conda-forge/osx-64::tk-8.6.10-hb0a8c7a_1
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010
....

conda activate atest

# testing with a public S3
tabix s3://3kricegenome/test/test.vcf.gz 9311_chr01:1010-1020
[W::hfile_add_scheme_handler] Couldn't register scheme handler for s3
[W::hfile_add_scheme_handler] Couldn't register scheme handler for s3+http
[W::hfile_add_scheme_handler] Couldn't register scheme handler for s3+https
[W::hfile_add_scheme_handler] Couldn't register scheme handler for s3w
[W::hfile_add_scheme_handler] Couldn't register scheme handler for s3w+http
[W::hfile_add_scheme_handler] Couldn't register scheme handler for s3w+https
[W::hfile_add_scheme_handler] Couldn't register scheme handler for dict
[W::hfile_add_scheme_handler] Couldn't register scheme handler for file
[W::hfile_add_scheme_handler] Couldn't register scheme handler for ftp
[W::hfile_add_scheme_handler] Couldn't register scheme handler for ftps
[W::hfile_add_scheme_handler] Couldn't register scheme handler for gopher
[W::hfile_add_scheme_handler] Couldn't register scheme handler for http
[W::hfile_add_scheme_handler] Couldn't register scheme handler for https
[W::hfile_add_scheme_handler] Couldn't register scheme handler for imap
[W::hfile_add_scheme_handler] Couldn't register scheme handler for imaps
[W::hfile_add_scheme_handler] Couldn't register scheme handler for pop3
[W::hfile_add_scheme_handler] Couldn't register scheme handler for pop3s
[W::hfile_add_scheme_handler] Couldn't register scheme handler for rtsp
[W::hfile_add_scheme_handler] Couldn't register scheme handler for scp
[W::hfile_add_scheme_handler] Couldn't register scheme handler for sftp
[W::hfile_add_scheme_handler] Couldn't register scheme handler for smb
[W::hfile_add_scheme_handler] Couldn't register scheme handler for smbs
[W::hfile_add_scheme_handler] Couldn't register scheme handler for smtp
[W::hfile_add_scheme_handler] Couldn't register scheme handler for smtps
[W::hfile_add_scheme_handler] Couldn't register scheme handler for telnet
[W::hfile_add_scheme_handler] Couldn't register scheme handler for tftp
[W::hfile_add_scheme_handler] Couldn't register scheme handler for gs
[W::hfile_add_scheme_handler] Couldn't register scheme handler for gs+http
[W::hfile_add_scheme_handler] Couldn't register scheme handler for gs+https
[E::hts_open_format] Failed to open file "s3://3kricegenome/test/test.vcf.gz" : Protocol not supported
Could not open "s3://3kricegenome/test/test.vcf.gz": Protocol not supported
```
If compiling `htslib` manually, from GitHub, it does work (using `brew` for supporting libs).

This is just the tip of the iceberg. Several packages (like `cyvcf2`, `pysam`, etc.) are compromised since they depends on `htsfile` and other libs.

**Comment by jmarshall** [comment]
@alanwilter: This is an unrelated problem that will be fixed by PR #25187.
