### ISSUE TITLE
dependency issue (samtools -> libcurses -> libtinfo)

### ISSUE THREAD

**Issue by andrewdelong** [bioconda/bioconda-recipes#1644]
Hi, 

Maybe a build configuration with how samtools depends on libncurses?

# PROBLEM
Reproduced below. Fresh Ubuntu 16.04 (x64), fresh Anaconda (x64, python2.7), empty `LD_LIBRARY_PATH`.

```
$ conda install -c bioconda samtools
$ samtools
samtools: /home/andrew/ext/anaconda2/bin/../lib/libtinfo.so.5: no version information available (required by /lib/x86_64-linux-gnu/libncurses.so.5) ...
samtools: relocation error: /lib/x86_64-linux-gnu/libncurses.so.5: symbol _nc_putchar, version NCURSES_TINFO_5.9.20150530 not defined in file libtinfo.so.5 with link time reference
```

Inside `/home/andrew/ext/anaconda2/lib` there is 
* `libtinfo.so.5`, and
* `libncursesw.so.5` (wide-char version), but
* notably no `libncurses.so.5` (non-wide-char version).

It seems my system `libncurses.so.5` is being found by samtools, rather than the one installed by conda (since there is no `anaconda2/lib/libncurses.so.5`), but then `anaconda2/lib/libtinfo.so.5` is found by my system libncurses, and the versions don't match.

# SOLUTION
I removed the `libtinfo.so[.5[.9]]` files from anaconda2/lib. Seems to work.
```
$ mv /home/andrew/ext/anaconda2/lib/libtinfo* /tmp
$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 1.3 (using htslib 1.3)

...
```

**Comment by croth1** [comment]
Can you check if installing with `conda install -c bioconda -c r samtools --override-channels` solves this issue?

A general problem in the samtools recipe is that the Makefile links against `-lcurses`, not against `-lncurses`. The samtools version here at bioconda uses ncurses from the `r` channel, which only provides `libncurses`, but no symlinks to `libcurses`. So if you use ncurses from the r-channel effectively the native lcurses is used.

I fixed the linking and some other stuff in this PR, maybe we should consider merging it. https://github.com/bioconda/bioconda-recipes/pull/1391

**Comment by johanneskoester** [comment]
@chapmanb I always thought the fixes of PR #1391 went into PR #1650. I guess something is still missing? Should we patch the Makefile to link to ncurses instead of curses?

**Comment by chapmanb** [comment]
Johannes -- I believe this report was prior the fixes in #1650 so it should work now. We do link against ncurses now -- the configure step (https://github.com/bioconda/bioconda-recipes/pull/1650/files#diff-af9278efb21daa738f1f15b62efe8376R19) picks up ncurses instead of curses so we don't need to patch the Makefile explicitly. Since curses-dev is no longer present in the container the approach in #1391 wouldn't work as is in my hands but the configure appears to do the right thing. 

Andrew -- sorry I should have followed up directly here. If you install the latest samtools it should hopefully work as expected and please let us know if not.

**Comment by johanneskoester** [comment]
Thanks for the clarification, Brad!

**Comment by yhoogstrate** [comment]
On my arch instance which has no libncurses5 installed I'm now getting a samtools error too:
`samtools: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory`

`ldd $(which samtools` gives:
```
	linux-vdso.so.1 (0x00007ffee83a8000)
	libncurses.so.5 => not found
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f6d355b6000)
	libz.so.1 => /home/user/miniconda2/envs/samtools/bin/../lib/libz.so.1 (0x00007f6d353a0000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f6d3519c000)
	libcurl.so.4 => /home/user/miniconda2/envs/samtools/bin/../lib/libcurl.so.4 (0x00007f6d34f39000)
	libcrypto.so.1.0.0 => /home/user/miniconda2/envs/samtools/bin/../lib/libcrypto.so.1.0.0 (0x00007f6d34b02000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f6d348e5000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f6d34544000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6d358ba000)
	libssl.so.1.0.0 => /home/user/miniconda2/envs/samtools/bin/../lib/./libssl.so.1.0.0 (0x00007f6d342ce000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f6d340c6000)

```

I was able to solve this by running `ln -s "$CONDA_PATH/lib/libncursesw.so.5.9" "$CONDA_PATH/lib/libncurses.so.5" `

**Comment by chapmanb** [comment]
Sometimes conda seems to get confused about installing ncurses. If you have this problem you should be able to fix it by installing the version that samtools is compiled against:
```
$CONDA_PATH/bin/conda update -y -c r ncurses
```
Hope this avoids the manual symlinking.

**Comment by croth1** [comment]
I've run into the same issue today on my arch as well. `ncurses` in the r channel for some reason does not provide the symlinks `libncurses.so.5` and `libncurses.so.5`, only `libncurses.so`, but our samtools explicitly linked against `libncurses.so.5`.

**Comment by johanneskoester** [comment]
Weird, how can that be, since we linked against the R channel samtools when building? @chapmanb any idea? Maybe they changed the package without incrementing the version?

**Comment by croth1** [comment]
A quick workaround is changing to conda-forge's version of ncurses.

`conda install -c conda-forge ncurses`

This version seems to be compatible with our build and also ships all symlinks - Seems like the current ncurses version in the r channel is broken.

**Comment by chapmanb** [comment]
Christian and Johannes -- thanks for investigating this and for the workaround. It looks like the r packaging team did bump the sub-version of ncurses so it now ships with libncursesw.so.5 instead of libncurses.so.5. I pushed a PR with more details that should fix this with a recompile (#2057). Thanks again for letting us know about the issue.

**Comment by johanneskoester** [comment]
Thanks, Brad!
