### ISSUE TITLE
Microassembler missing in latest Scalpel recipe

### ISSUE THREAD

**Issue by guillaumecharbonnier** [bioconda/bioconda-recipes#19844]
Using latest conda recipe for `scalpel`, 
`scalpel-discovery  --single` fails because `Microassembler` is not available where it is looking for:
```
$PREFIX/share/scalpel-0.5.4-1/Microassembler/Microassembler: No such file or directory
```

Mentionning recipe contributors:
@Luobiny @chapmanb @epruesse @dpryan79

**Comment by dpryan79** [comment]
It looks like the Microassembler source code was installed rather than being compiled first. I really don't know why microassembler isn't getting compiled, it's explicitly mentioned in the Makefile.

**Comment by chapmanb** [comment]
Thanks for the report. I took a look at this and it appears to be a compilation problem due to changes in the environmental variables for conda builds. It no longer finds the bamtools include files and fails. I have a fix and am testing right now. Will try to upload first thing tomorrow, thanks again for identifying this.

**Comment by chapmanb** [comment]
Thanks again for reporting this problem. We've fixed it in the latest build (0.5.4_2) and hopefully all will work cleanly now. Please let us know if you run into more issues.

**Comment by eeleclair** [comment]
Hello, I am having the same error and found this page (thank you, Google).  But where can I get the **0.5.4_2** version of Scalpel?    Sourceforge has only **0.5.4** dated 1/11/2018.

**Comment by YuanfengZhang** [comment]
> Hello, I am having the same error and found this page (thank you, Google). But where can I get the **0.5.4_2** version of Scalpel? Sourceforge has only **0.5.4** dated 1/11/2018.

Watch the resource they offer. This is a conda package, and requires samtools, bamtools and sereval other pkgs. So the best practice I propose is to create a new conda env. You can copy following cmdlns to run in shell on Linux system if you are a new hand:
`conda create -n somatic`

`conda install -c bioconda scalpel -y`

When you want to run scalpel, 
`conda activate somatic`
and scalpel-discovery will be avaliable.

Simply type `scalpel-discovery` and you shall see message like below:

> Local date and time: Tue Oct 12 18:46:09 2021
> 
> Program: scalpel-discovery (micro-assembly variant detection)
> Version: 0.5.4 (beta), January 11 2018
> Contact: Giuseppe Narzisi <gnarzisi@nygenome.org>
> 
> usage: scalpel-discovery <COMMAND> [OPTIONS]
> 
> COMMAND:
> 
>     --help    : this (help) message
>     --verbose : verbose mode
> 
>     --single  : single exome study 
>     --denovo  : family study (mom,dad,affected,sibling)
>     --somatic : normal/tumor study

I successfully ran a somatic analysis using this version, no error happened.

**Comment by Stack7** [comment]
I have recently installed scalpel 0.5.4 through bioconda, unluckily the asnwer I found here so far haven't solved the issue. The very same error is still there. I am working on a Fedora 40 HPC, in a conda environment with version Python 3.12.6 . 
thank you very much in advance!
