### ISSUE TITLE
bioconductor-go.db postlink failure due to download file URL md5sums not matching

### ISSUE THREAD

**Issue by hermidalc** [bioconda/bioconda-recipes#36499]
Seems same as #36436 but with different package, I guess #36423 intends to fix it

```
ERROR conda.core.link:_execute(730): An error occurred while installing package 'bioconda::bioconductor-go.db-3.14.0-r41hdfd78af_0'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package bioconda::bioconductor-go.db-3.14.0-r41hdfd78af_0
location of failed script: /home/hermidalc/soft/mambaforge/envs/gex-analysis/bin/.bioconductor-go.db-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: /home/hermidalc/soft/mambaforge/envs/gex-analysis/share/bioconductor-go.db-3.14.0-0/GO.db_3.14.0.tar.gz: FAILED
/home/hermidalc/soft/mambaforge/envs/gex-analysis/share/bioconductor-go.db-3.14.0-0/GO.db_3.14.0.tar.gz: FAILED
/home/hermidalc/soft/mambaforge/envs/gex-analysis/share/bioconductor-go.db-3.14.0-0/GO.db_3.14.0.tar.gz: FAILED
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum eef1de573f2304a4c12e64da2d9f55bd:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GO.db_3.14.0.tar.gz
https://bioarchive.galaxyproject.org/GO.db_3.14.0.tar.gz
https://depot.galaxyproject.org/software/bioconductor-go.db/bioconductor-go.db_3.14.0_src_all.tar.gz

stderr:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   406  100   406    0     0   1141      0 --:--:-- --:--:-- --:--:--  1140
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    457      0 --:--:-- --:--:-- --:--:--   458
md5sum: WARNING: 1 computed checksum did NOT match
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    362      0 --:--:-- --:--:-- --:--:--   362
md5sum: WARNING: 1 computed checksum did NOT match

return code: 1

kwargs:
{}

Traceback (most recent call last):
  File "/home/hermidalc/soft/mambaforge/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
    return func(*args, **kwargs)
  File "/home/hermidalc/soft/mambaforge/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/hermidalc/soft/mambaforge/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 143, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "/home/hermidalc/soft/mambaforge/lib/python3.9/site-packages/mamba/mamba_env.py", line 173, in mamba_install
    handle_txn(conda_transaction, prefix, args, True)
  File "/home/hermidalc/soft/mambaforge/lib/python3.9/site-packages/mamba/linking.py", line 44, in handle_txn
    unlink_link_transaction.execute()
  File "/home/hermidalc/soft/mambaforge/lib/python3.9/site-packages/conda/core/link.py", line 281, in execute
    self._execute(tuple(concat(interleave(self.prefix_action_groups.values()))))
  File "/home/hermidalc/soft/mambaforge/lib/python3.9/site-packages/conda/core/link.py", line 744, in _execute
    raise CondaMultiError(tuple(concatv(
```

**Comment by daler** [comment]
Yes, there is a large migration happening right now to fix this for all bioconductor data packages. As of writing this, `bioconductor-go.db` hasn't been updated yet but should be soon.

**Comment by hermidalc** [comment]
> Yes, there is a large migration happening right now to fix this for all bioconductor data packages. As of writing this, `bioconductor-go.db` hasn't been updated yet but should be soon.

Thank you @daler!

**Comment by amizeranschi** [comment]
I am seeing this same issue with the package `bioconductor-go.db`, and also with `bioconductor-org.hs.eg.db`.

@daler is there any place where we can track the progress of this migration that you mention, to see when these package should be able to install correctly?

**Comment by daniel-nebdal** [comment]
Looks like the same thing for `BSgenome.Hsapiens.UCSC.hg38` too . Until this migration finishes, I guess it needs something like #31349 (adding -L to make curl follow redirects)? 

That's probably a good practice in general when using curl in scripts; following redirects is probably expected behavior.

**Comment by hermidalc** [comment]
For now the workaround is to use conda/mamba to install everything **but** the problematic DB packages, then with the conda environment activated using R to manually install them, e.g. 
```R
library(BiocManager)
install("GO.db", update = FALSE)
```

**Comment by daler** [comment]
https://github.com/bioconda/bioconda-recipes/pull/36797 has the PR, but this has been running on the special "bulk" infrastructure to avoid tying up CI resources on regular PRs. So no good place to check progress. All data packages *should* be fixed now, but please ping me if you find something missing!

The best way to check if a particular package has been updated is to look for it on https://anaconda.org/bioconda, check the "Files" tab, and inspect the time it was uploaded. 

For the packages specifically mentioned here:

- [`BSgenome.Hsapiens.UCSC.hg38`](https://anaconda.org/bioconda/bioconductor-bsgenome.hsapiens.ucsc.hg38)
- [`bioconductor-go.db`](https://anaconda.org/bioconda/bioconductor-go.db/files)
- [`bioconductor-org.hs.eg.db`](https://anaconda.org/bioconda/bioconductor-org.hs.eg.db)

See #36797 for the details.

@hermidalc @daniel-nebdal @amizeranschi please test this locally and confirm it's fixed (and if so we can close this)

**Comment by amizeranschi** [comment]
@daler many thanks for following up on this. I can confirm that all the BioC I was working with are now installing properly from bioconda.

**Comment by hermidalc** [comment]
@daler thank you very much, just tested creating new env with multiple bioconductor dbs and all is working again

**Comment by RonaldOellers** [comment]
for me [bioconductor-go.db](https://anaconda.org/bioconda/bioconductor-go.db/files) is still a problem, I am installing from within snakemake using mamba as a conda frontend. For me it is a downstream dependency, probablyof some package used for annotation. So I am not sure how to fix this without just checking every package in the .yaml by hand.

**Comment by TobyBaril** [comment]
I am having the same issue with ```bioconductor-genomeinfodbdata-1.2.7-r41hdfd78af_0```, any idea on timeframe for a solution?

**Comment by amizeranschi** [comment]
@TobyBaril there's a more up to date discussion here: https://github.com/bioconda/bioconda-recipes/issues/37906
