### ISSUE TITLE
Missing ttf-dejavu/fontconfig dependencies for fastqc

### ISSUE THREAD

**Issue by jrderuiter** [bioconda/bioconda-recipes#5026]
If fontconfig or ttf-dejavu are not installed, fastqc can produce the following error:

```
java.lang.Error: Probable fatal error:No fonts found
```

which is identical to the error described here: https://stackoverflow.com/questions/14066525/java-lang-error-probable-fatal-errorno-fonts-found. This issue is at least encountered in the snakemake container used by snakemake-wrappers.

I think this error is not necessarily specific to fastqc, but likely a more general dependency of openjdk which is currently missing. 

We can easily fix it for fontconfig by adding the dependency to the fastqc or openjdk recipes. However, for ttf-dejavu there does not seem to be an existing package as far as I can see. I have no experience with creating non-R/Python packages, so was wondering if someone would be prepared to build a ttf-dejavu package or otherwise provide me with pointers on how to do so.

**Comment by bgruening** [comment]
@jrderuiter interesting! Can you move this issue to conda-forge? I guess we need to discuss this over there as it seems a general problem and general package.

**Comment by jrderuiter** [comment]
Done: https://github.com/conda-forge/staged-recipes/issues/3164.

**Comment by bgruening** [comment]
Thanks!

**Comment by epruesse** [comment]
The conda-forge openjdk package has the missing fonts (https://github.com/conda-forge/openjdk-feedstock/blob/master/recipe/build.sh#L24). The issue occurs only if openjdk is pulled from defaults.

**Comment by rspreafico** [comment]
Confirming this issue. As a result, the mulled Biocontainer based [on this Bioconda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/fastqc/meta.yaml) is not functional. The default OpenJDK should download ttf-dejavu the same way the conda-forge version does.

**Comment by daler** [comment]
@rspreafico it looks like the fastqc container was last modified in May, while the missing fonts were added to the conda-forge openjdk in June. #6518 bumps the build number for fastqc. Once merged this should result in a new container containing an updated open-jdk that you can test.

**Comment by rspreafico** [comment]
Thank you for the quick reply and turnaround, this is awesome

**Comment by bgruening** [comment]
@rspreafico the container will be online in an ~1h.
Please reopen if this does not solve the problem.

**Comment by rspreafico** [comment]
Hi @daler @bgruening unfortunately it seems that the new container still suffers from the same issue:

```
docker run -w `pwd` -v `pwd`:`pwd` --rm -i quay.io/biocontainers/fastqc:0.11.5--pl5.22.0_3 fastqc test.fastq.gz
[...]
Analysis complete for test.fastq.gz
Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.
```

**Comment by epruesse** [comment]
It's probably missing `freetype`.

**Comment by epruesse** [comment]
It's installing the "wrong" openjdk:

```
$ docker run quay.io/biocontainers/fastqc:0.11.5--pl5.22.0_3 sh -c 'grep -H channel /usr/local/conda-meta/openjdk*'
/usr/local/conda-meta/openjdk-8.0.121-1.json:  "channel": "https://repo.continuum.io/pkgs/free/linux-64",
/usr/local/conda-meta/openjdk-8.0.121-1.json:  "schannel": "defaults",
```

**Comment by epruesse** [comment]
@bioconda/core I'm not very familiar with the way the quay docker images are built. Shouldn't conda-forge be preferred over defaults? The fastqc image contains the (broken, missing fonts) openjdk from defaults for some reason.

**Comment by rvalieris** [comment]
in theory yes.
I think we could add a test to the package to check if the fonts are available.

**Comment by rvalieris** [comment]
I just did a more realistically test here: https://github.com/bioconda/bioconda-recipes/pull/6576, and the recipe built just fine, however this test fails when I tried it with quay.io/biocontainers/fastqc. 
which implies during this build and test it is using conda-forge::openjdk as intended. however the quay container ends up with the defaults::openjdk.

I also checked containers of other bioconda packages  picard, gatk, cromwell and they also contain defaults::openjdk.

to be honest I am not sure where the issue is, I am not familiar with how the quay images are built either.

**Comment by bgruening** [comment]
@epruesse @rvalieris the container that is build during testing is push directly. So it should be the test container. I need some time to look at it and run it locally, but if you run it with debug, the `mulled-build` command and/or the `involucro` command should have the channel order printed. You should also see the packages and the channels in this log.

**Comment by epruesse** [comment]
@bgruening I believe the defaults channel is active in the mulled builds: https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/pkg_test.py#L80

W.r.t. bioconda-utils and the mulled-build ... I just tried to have a look at it, but the jumping about between various tools makes it hard to figure out what's going on at all, even with `--loglevel=debug`. It's not working at all with `simulate-travis.py` and `~/.bioconda` for me (I get `Can't convert NoneType to str implicitly` type Python errors).

Where should the image file end up even?

**Comment by epruesse** [comment]
Checked that already ... nothing there. I'll post if I find the time to dig into this.

**Comment by MWorksGH** [comment]
Using quay.io/biocontainers/fastqc:0.11.6--pl5.22.0_0 and the error persists, hope someone can get some time to solve this. :)

**Comment by bgruening** [comment]
@MWorksGH could you share the entire installation plan with us? Please make sure you are using the correct channel order: https://bioconda.github.io/#set-up-channels

**Comment by raonyguimaraes** [comment]
Solved this problem on Ubuntu using: sudo apt install ttf-dejavu
Hope this gets sorted at some point.

**Comment by ewels** [comment]
@bgruening - here's a minimal example `Dockerfile`:

```dockerfile
FROM continuumio/miniconda
MAINTAINER Phil Ewels <phil.ewels@scilifelab.se>

RUN conda config --add channels defaults \
 && conda config --add channels conda-forge \
 && conda config --add channels bioconda \
 && conda install -y fastqc=0.11.7
```

Building:

<details>
<summary>Click to expand log</summary>

```
docker build . -t fastqc_test
Sending build context to Docker daemon  133.2MB
Step 1/3 : FROM continuumio/miniconda
latest: Pulling from continuumio/miniconda
4176fe04cefe: Pull complete
3727fa417d9f: Pull complete
30fd03596c22: Pull complete
8d7f8695c318: Pull complete
Digest: sha256:c93288b9bb35847e575d5ee8f3469551d6c769812bed2ed59968af86897b0791
Status: Downloaded newer image for continuumio/miniconda:latest
 ---> 53447bc91028
Step 2/3 : MAINTAINER Phil Ewels <phil.ewels@scilifelab.se>
 ---> Running in 43967e10080f
Removing intermediate container 43967e10080f
 ---> 3fd3b0a9c1eb
Step 3/3 : RUN conda config --add channels defaults  && conda config --add channels conda-forge  && conda config --add channels bioconda  && conda install -y fastqc=0.11.7
 ---> Running in 6cbdbc89ded1
Warning: 'defaults' already in 'channels' list, moving to the top
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.4.11

Please update conda by running

    $ conda update -n base conda


font-ttf-dejavu-sans-mono 2.37: ########## | 100%
perl 5.22.0.1: ########## | 100%
fastqc 0.11.7: ########## | 100%
openjdk 8.0.121: ########## | 100%

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - fastqc=0.11.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    font-ttf-dejavu-sans-mono-2.37|       h6964260_0         386 KB
    perl-5.22.0.1              |                0        15.1 MB  conda-forge
    fastqc-0.11.7              |       pl5.22.0_0         9.6 MB  bioconda
    openjdk-8.0.121            |                1        64.2 MB
    ------------------------------------------------------------
                                           Total:        89.3 MB

The following NEW packages will be INSTALLED:

    fastqc:                    0.11.7-pl5.22.0_0 bioconda
    font-ttf-dejavu-sans-mono: 2.37-h6964260_0
    openjdk:                   8.0.121-1
    perl:                      5.22.0.1-0        conda-forge


Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Removing intermediate container 6cbdbc89ded1
 ---> c3cf11270f71
Successfully built c3cf11270f71
Successfully tagged fastqc_test:latest
```

</details>

---

Then running a test:
```
$ docker container run -it fastqc_test bash
```

<details>
<summary>Click to expand log</summary>

```
# [ pasted mini fastq file ]

root@39ea321534b8:/# fastqc test.fq
Started analysis of test.fq
Analysis complete for test.fq
Exception in thread "Thread-1" java.lang.Error: Probable fatal error:No fonts found.
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1236)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1100)
	at sun.font.SunFontManager.findOtherDeferredFont(SunFontManager.java:1037)
	at sun.font.SunFontManager.findDeferredFont(SunFontManager.java:1054)
	at sun.font.SunFontManager.findFont2D(SunFontManager.java:2256)
	at sun.font.SunFontManager.getDefaultPhysicalFont(SunFontManager.java:1220)
	at sun.font.SunFontManager.initialiseDeferredFont(SunFontManager.java:1106)
	at sun.font.CompositeFont.doDeferredInitialisation(CompositeFont.java:263)
	at sun.font.CompositeFont.getSlotFont(CompositeFont.java:352)
	at sun.font.CompositeStrike.getStrikeForSlot(CompositeStrike.java:78)
	at sun.font.CompositeStrike.getFontMetrics(CompositeStrike.java:93)
	at sun.font.FontDesignMetrics.initMatrixAndMetrics(FontDesignMetrics.java:359)
	at sun.font.FontDesignMetrics.<init>(FontDesignMetrics.java:350)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:302)
	at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:855)
	at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.paint(QualityBoxPlot.java:88)
	at javax.swing.JComponent.print(JComponent.java:1202)
	at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:68)
	at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199)
	at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131)
	at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
	at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
	at java.lang.Thread.run(Thread.java:745)

root@39ea321534b8:/#
```

</details>

---

So the channel order should be correct I think, but I'm still getting the error.

Note - that if I explicitly add `conda-forge::openjdk` to the `Dockerfile` conda install command, everything is fine:

```dockerfile
FROM continuumio/miniconda
MAINTAINER Phil Ewels <phil.ewels@scilifelab.se>

RUN conda config --add channels defaults \
 && conda config --add channels conda-forge \
 && conda config --add channels bioconda \
 && conda install -y conda-forge::openjdk fastqc=0.11.7
```

<details>
<summary>Click to expand log</summary>

```
$ docker build . -t fastqc_test_2

Sending build context to Docker daemon  133.2MB
Step 1/3 : FROM continuumio/miniconda
 ---> 53447bc91028
Step 2/3 : MAINTAINER Phil Ewels <phil.ewels@scilifelab.se>
 ---> Using cache
 ---> 3fd3b0a9c1eb
Step 3/3 : RUN conda config --add channels defaults  && conda config --add channels conda-forge  && conda config --add channels bioconda  && conda install -y conda-forge::openjdk fastqc=0.11.7
 ---> Running in bb556e1cccc6
Warning: 'defaults' already in 'channels' list, moving to the top
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.4.11

Please update conda by running

    $ conda update -n base conda


openjdk 8.0.144: ########## | 100%
font-ttf-dejavu-sans-mono 2.37: ########## | 100%
perl 5.22.0.1: ########## | 100%
fastqc 0.11.7: ########## | 100%

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - conda-forge::openjdk
    - fastqc=0.11.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openjdk-8.0.144            |   zulu8.23.0.3_1        69.3 MB  conda-forge
    font-ttf-dejavu-sans-mono-2.37|       h6964260_0         386 KB
    perl-5.22.0.1              |                0        15.1 MB  conda-forge
    fastqc-0.11.7              |       pl5.22.0_0         9.6 MB  bioconda
    ------------------------------------------------------------
                                           Total:        94.4 MB

The following NEW packages will be INSTALLED:

    fastqc:                    0.11.7-pl5.22.0_0      bioconda
    font-ttf-dejavu-sans-mono: 2.37-h6964260_0
    openjdk:                   8.0.144-zulu8.23.0.3_1 conda-forge
    perl:                      5.22.0.1-0             conda-forge


Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Removing intermediate container bb556e1cccc6
 ---> d8a0723e043e
Successfully built d8a0723e043e
Successfully tagged fastqc_test_2:latest
```

</details>

```
$ docker container run -it fastqc_test bash
```

```
# [ pasted mini fastq file ]

root@15a71d6a5e95:/# fastqc test.fq
Started analysis of test.fq
Analysis complete for test.fq
root@15a71d6a5e95:/#
```

---

So it seems that this can be fixed fairly easily by explicitly requiring the conda-forge version of openjdk. Could this be added to the bioconda FastQC recipe or something?

**Comment by c-guzman** [comment]
Just wanted to post on here that this is still an issue.

**Comment by mbargull** [comment]
xref: https://github.com/bioconda/bioconda-recipes/pull/8588#issuecomment-380933590 ff.

**Comment by mbargull** [comment]
Resolved by gh-8588 and gh-8610.

**Comment by cbrueffer** [comment]
I'm afraid the issue is back:

```
$ conda create -n fastqctest fastqc
Solving environment: done

## Package Plan ##

  environment location: /home/chris/miniconda3/envs/fastqctest

  added / updated specs: 
    - fastqc


The following NEW packages will be INSTALLED:

    fastqc:  0.11.7-pl5.22.0_1 bioconda   
    openjdk: 8.0.121-1                    
    perl:    5.22.0.1-0        conda-forge
```

**Comment by chapmanb** [comment]
Thanks for catching this, it is so frustrating this keeps coming back. +1 on pining the openjdk version so we get the right thing.

**Comment by mbargull** [comment]
Ah, makes sense, `fastqc 0.11.7-pl5.22.0_1` must be moved from the `main` label.
@bioconda/core can someone with access to the channel do that? (Or you could give me -- also as `mbargull` on anaconda.org -- access so I can take care of it.)

**Comment by bgruening** [comment]
Hopefully done.

**Comment by cbrueffer** [comment]
Still happening, although the fonts are being installed now. The version being installed is ```0.11.7-pl5.22.0_0 ```, do all the ```-pl5.22.0``` versions of the packages need to be invalidated?

```
$ conda create -n foo fastqc
Solving environment: done

## Package Plan ##

  environment location: /home/chris/miniconda3/envs/foo

  added / updated specs: 
    - fastqc


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    font-ttf-dejavu-sans-mono-2.37|       h6964260_0         386 KB
    fastqc-0.11.7              |       pl5.22.0_0         9.6 MB  bioconda
    ------------------------------------------------------------
                                           Total:        10.0 MB

The following NEW packages will be INSTALLED:

    fastqc:                    0.11.7-pl5.22.0_0 bioconda   
    font-ttf-dejavu-sans-mono: 2.37-h6964260_0              
    openjdk:                   8.0.121-1                    
    perl:                      5.22.0.1-0        conda-forge
```

**Comment by mbargull** [comment]
Yes, that's to be expected. Is there any reason why `defaults::openjdk=8.0.121_1` + `font-ttf-dejavu-sans-mono=2.37=h6964260_0` wouldn't work? I'm always hesitant to call something broken (meaning, labelling `bioconda::fastqc=0.11.7=pl5.22.0_0` as `broken`) if it isn't necessarily.

**Comment by cbrueffer** [comment]
I can't think of any reason for why it shouldn't work. FYI, I tried the ```bioconda::fastqc=0.11.7=4``` package resulting from my fastqc commit yesterday and it works.

**Comment by apeltzer** [comment]
Ok, still having some issues here. I first thought that the channels order was causing this, but thats not the case:

Here's my `environment.yaml` and I create the environment like this:

https://github.com/nf-core/eager/blob/dev/environment.yml

`conda env create -f environment.yml`

Unfortunately, when calling `fastqc` in there, I reproducibly get this error:

```
fastqc                                                                                                                                                          (nf-core-eager-2.1.0dev) 
java: symbol lookup error: /home/alex/.conda/envs/nf-core-eager-2.1.0dev/bin/../lib/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var
```

cf https://github.com/nf-core/eager/issues/67

**Comment by bgruening** [comment]
From where is your openjdk coming, from which channel?

**Comment by apeltzer** [comment]
Conda-forge

```
openjdk                   8.0.144          zulu8.23.0.3_2    conda-forge

```

**Comment by apeltzer** [comment]
Couldn't find a solution for this atm, quite clueless what is the issue here...

**Comment by stevekm** [comment]
When I try to use the method suggested by @raonyguimaraes  I get an error under Ubuntu 16.04:

```
Package ttf-dejavu is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-dejavu-extra fonts-dejavu-core

E: Package 'ttf-dejavu' has no installation candidate
```

maybe this is a recent change because I think I have a Dockerfile from this past May where this appeared to have worked..

**Comment by jvolkening** [comment]
Just want to add that I ran into this problem today, and it doesn't appear to matter where the openjdk package comes from (for me). Running on the vanilla AWS AMI image and within the continuumio/miniconda3 docker image, `fastqc` doesn't work unless both the `fontconfig` and at least one `font-ttf-*` package is installed. Interestingly, the font package can then be removed and `fastqc` will continue to work.

```
# Name                    Version                   Build  Channel
fastqc                    0.11.8                        0    bioconda
openjdk                   11.0.1               h470a237_2    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
```

**Comment by jvolkening** [comment]
> Interestingly, the font package can then be removed and `fastqc` will continue to work.

To clarify this, FastQC doesn't seem to need the fonts themselves to be present, just the entries in the fontconfig cache.

**Comment by apeltzer** [comment]
I will submit an updated recipe now that adds 

```
- fontconfig > 2 
- font-ttf-dejavu-sans-mono > 2
```

To make sure this is solved. It keeps being annoying when this breaks from time to time, so adding these two should make everything more stable.

**Comment by bgruening** [comment]
It seems no one complained anymore ... so closing this again. Fingers crossed thanks all!

**Comment by ialbert** [comment]
I will note here that the tool runs but the fonts are quite ugly, 

the generated image looks like something generated in the 90s. (conda on a Mac)

![image](https://i.imgur.com/zU1pKZm.png)

**Comment by allysonFDSmtp** [comment]
Hi every one, 
Looks like there is still a problem with Java because when I try to process a fastqc into my env conda I have this error : 

```
Failed to process file sample1_R1_001.fastq.gz
  java.lang.RuntimeException: Fontconfig head is null, check your fonts or fonts configuration
        at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1263)
        at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:221)
        at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:105)
        at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:696)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:352)
        at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:309)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:309)
        at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:55)
        at java.desktop/sun.font.PlatformFontInfo.createFontManager(PlatformFontInfo.java:37)
        at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:51)
        at java.desktop/sun.font.SunFontManager.getInstance(SunFontManager.java:242)
        at java.desktop/sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:260)
        at java.desktop/sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:862)
        at uk.ac.babraham.FastQC.Graphs.QualityBoxPlot.paint(QualityBoxPlot.java:88)
        at java.desktop/javax.swing.JComponent.print(JComponent.java:1274)
        at uk.ac.babraham.FastQC.Modules.AbstractQCModule.writeDefaultImage(AbstractQCModule.java:68)
        at uk.ac.babraham.FastQC.Modules.PerBaseQualityScores.makeReport(PerBaseQualityScores.java:199)
        at uk.ac.babraham.FastQC.Report.HTMLReportArchive.<init>(HTMLReportArchive.java:131)
        at uk.ac.babraham.FastQC.Analysis.OfflineRunner.analysisComplete(OfflineRunner.java:178)
        at uk.ac.babraham.FastQC.Analysis.AnalysisRunner.run(AnalysisRunner.java:110)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```
I have those library in my env conda 

openjdk                   17.0.11              h24d6bf4_0    conda-forge
fastqc                    0.11.7               hdfd78af_7    bioconda
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                hd3eb1b0_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-anaconda            1                    h8fa9717_0  
fonts-conda-ecosystem     1                    hd3eb1b0_0

Thank you for your help
