### ISSUE TITLE
Manta is Python 2-only and built using boost-cpp 1.85.0 which is not vailable for Python 2

### ISSUE THREAD

**Issue by ravihansa3000** [bioconda/bioconda-recipes#53419]
Manta run fails with 
```
GetChromDepth: error while loading shared libraries: libboost_filesystem.so.1.85.0: cannot open shared object file: No such file or directory
GetAlignmentStats: error while loading shared libraries: libboost_filesystem.so.1.85.0: cannot open shared object file: No such file or directory
```

However, boost=1.85.0 cannot be installed in a conda env created with Python2 since it isn't available

This breaks after this change - https://github.com/bioconda/bioconda-recipes/pull/52517
The previous build works ok
cc @dslarm 

```
conda info

     active environment : base
    active env location : /home/users/nus/csiv180/anaconda3
            shell level : 1
       user config file : /home/users/nus/csiv180/.condarc
 populated config files : /home/users/nus/csiv180/.condarc
          conda version : 24.9.1
    conda-build version : 24.5.1
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen3
                          __conda=24.9.1=0
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /home/users/nus/csiv180/anaconda3  (writable)
      conda av data dir : /home/users/nus/csiv180/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/users/nus/csiv180/anaconda3/pkgs
                          /home/users/nus/csiv180/.conda/pkgs
       envs directories : /home/users/nus/csiv180/anaconda3/envs
                          /home/users/nus/csiv180/.conda/envs
               platform : linux-64
             user-agent : conda/24.9.1 requests/2.32.2 CPython/3.12.4 Linux/4.18.0-305.25.1.el8_4.x86_64 rhel/8.4 glibc/2.28 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 32036:32036
             netrc file : None
           offline mode : False
```

**Comment by holtgrewe** [comment]
Having the same issue, I could workaround this by pinning manta to `manta=1.6.0=py27_0`.

**Comment by dslarm** [comment]
I'm taking a look. 

Background is that the basic change of the build was to build the binary from source - and to do that with dynamic instead of static boost library, which would account for it not finding the boost library at runtime. Using dynamic boost meant we could use bioconda's own boost library build rather than rebuilding it - making things faster to build.

**Comment by dslarm** [comment]
#53424 is a PR which should fix this.

**Comment by martin-g** [comment]
@ravihansa3000 @holtgrewe Please test the artifacts at https://github.com/bioconda/bioconda-recipes/pull/53424#issuecomment-2611730550

**Comment by ravihansa3000** [comment]
Thanks for the quick turnaround! I've tested and verified the latest build.

**Comment by sindacatobioinfo** [comment]
Please, add the fixed 1.6 version to conda. I tried to use manta.1.6.0 using conda and continued to get the libboost_filesystem.so.1.85.0 error. Even adding boost-cpp dependence. The error persists.
