### ISSUE TITLE
krakenhll: needed executables not in PATH

### ISSUE THREAD

**Issue by stephenturner** [bioconda/bioconda-recipes#8474]
Trying to use [krakenhll](https://bioconda.github.io/recipes/krakenhll/README.html) as directed in the krakenhll manual and help. 

1. **`build_taxdb`** isn't in PATH. This is needed to build `DB_DIR/taxDB` as specified in the [krakenhll usage documentation](https://github.com/fbreitwieser/krakenhll#usage). I could solve this problem using something like this, but would be better if `build_taxdb` was in PATH.
    ```bash
    $(dirname $(which krakenhll))/../libexec/build_taxdb <taxonomy/names.dmp> <taxonomy/nodes.dmp> > taxDB
    ```
1. **`read_merger.pl`** isn't in PATH. Error below.
    ```
    Can't exec "read_merger.pl": No such file or directory at 
    /home/user/miniconda3/envs/krakenhll/bin/krakenhll line 253.
    krakenhll: can't exec read_merger.pl: No such file or directory
    ```

Related to the latter problem, I'm trying to run krakenhll with `--fastq-input --paired --gzip-compressed <read_1.fq.gz> <read_2.fq.gz>` but this is failing. I worked around this by first downloading the read merger script, merging the two fastq.gz files into a fasta, then running krakenhll on that fasta. E.g.

```sh
# get the script
wget https://raw.githubusercontent.com/fbreitwieser/krakenhll/master/scripts/krakenhll-read_merger.pl

# Merge the fastqs manually
perl krakenhll-read_merger.pl --fq --gz read_1.fq.gz read_1.fq.gz | gzip -c > reads.fasta.gz

# Run krakenhll on the manually concatenated reads in the fasta
krakenhll <args> --fasta-input --gzip-compressed reads.fasta.gz
```

cc @fbreitwieser @druvus @DerrickWood

**Comment by fbreitwieser** [comment]
Hi @stephenturner, thanks for filing the bug. It's in KrakenHLL and I'll fix it soon.

**Comment by fbreitwieser** [comment]
Should be fixed with KrakenHLL release v0.4.1

**Comment by stephenturner** [comment]
excellent, looking forward to the bioconda update cc @kternus

**Comment by tomkinsc** [comment]
@stephenturner: Now that KrakenHLL has been updated upstream, PR #8927 has updated the conda package to the latest version of KrakenHLL. Can you please check to see if this issue is resolved by the new package?

**Comment by stephenturner** [comment]
`build_taxdb` still not in path. 

```
$ krakenhll --version
KrakenHLL version 0.4.2
Copyright 2017, Florian Breitwieser (fbreitwieser@jhu.edu)
Copyright 2013-2017, Derrick Wood (dwood@cs.jhu.edu) for Kraken
$ which build_taxdb
/usr/bin/which: no build_taxdb in <PATH>
```

Will run to see if it can work from paired gzipped fastq instead of doing manually.

**Comment by tomkinsc** [comment]
How about now?

**Comment by stephenturner** [comment]
Works, thanks! `build_taxdb` is now in the PATH, and so are the necessary utilities to run directly from gzipped fastq instead of the workaround above.
